language: cpp
dist: xenial
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake

before_script:
  - sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++

script:
  - mkdir {build,build-debug,build-release}
  # Standard Build
  - pushd build
  - cmake ..
  - make
  - ctest -VV
  - popd
  # Debug Build
  - pushd build-debug
  - cmake .. -DCMAKE_BUILD_TYPE:STRING=Debug
  - make
  - ctest -VV
  - popd
  # Release Build
  - pushd build-release
  - cmake .. -DCMAKE_BUILD_TYPE:STRING=Release
  - make
  - ctest -VV
  - popd